name: NxtHealthBar
version: 1.2.0
description: 简单的怪物生命条
author: Thetestgame
authors: [Thetestgame]
main: com.nxtinc.thetestgame.healthbar.PluginMain
softdepend: [Vault]

commands:
   nhb:
      description: 基本Nxt管理员指令
      usage: /<command> [Sub Command]
      permission: nxthealtbar.op
      permission-message: 你没有足够的权限

permissions:  
    nxthealthbar.op:
        description: 允许用户使用 /nhb
        default: op 
